WORKDIR /path/to/workdir

Инструкция WORKDIR устанавливает рабочий каталог для любых инструкций RUN, CMD, и ENTRYPOINT,
которые следуют за ней в Dockerfile. Если не существует, он будет создан,
даже если он не используется ни в одной последующей инструкции Dockerfile.COPY ADD WORKDIR

Инструкцию WORKDIR можно использовать несколько раз в Dockerfile.
Если указан относительный путь, он будет относительным к пути предыдущей WORKDIR инструкции. Например:

WORKDIR /a
WORKDIR b
WORKDIR c
RUN pwd  - Вывод последней pwd команды в этом Dockerfile будет следующим /a/b/c.

Инструкция WORKDIR может разрешить переменные среды, установленные ранее с помощью ENV.
Вы можете использовать только переменные среды, явно установленные в Dockerfile. Например:

ENV DIRPATH=/path
WORKDIR $DIRPATH/$DIRNAME
RUN pwd - Вывод последней pwd команды в этом Dockerfile будет следующим: /path/$DIRNAME